### ISSUE TITLE
confirmation_id is not getting viewed.

### ISSUE THREAD

**Issue by Subhadeep0506** [tecladocode/advanced-rest-api-lecture-codes#2]
@jslvtr 
{{url}}/user/1 -> this request as supposed to show the confirmation_id hexcode is not showing in postman. I changed the pre_dump method too, still same issue.
Any suggestions on this is appreciated( i also tried your github end code for this section, did not seem to work)

**Comment by sukanyabag** [comment]
> @jslvtr {{url}}/user/1 -> this request as supposed to show the confirmation_id hexcode is not showing in postman. I changed the pre_dump method too, still same issue. Any suggestions on this is appreciated( i also tried your github end code for this section, did not seem to work)

@jslvtr kindly please look into the issue. I tried it too, but confirmation id doesn't show up after sending the request, inspite of all possible code updates.
